### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by jakobmelti** [hawshemi/Linux-Optimizer#68]
Hey, i see you removed "net.ipv4.tcp_fastopen = 3" is there any reason ?

**Comment by scythianeagle** [comment]
no,just testing

**Comment by hawshemi** [comment]
I read some articles about TCP_FastOpen and TCP_NoDelay. They seem to work well, but they mostly don't affect anything!
After testing my various servers, I noticed it's better to stick to the default rather than changing TCP_FO and TCP_ND parameters.


https://blog.apnic.net/2021/07/05/tcp-fast-open-not-so-fast/

https://brooker.co.za/blog/2024/05/09/nagle.html
